---

- name: Install Certbot.
  package:
    name: 
      - certbot
      - python3-certbot-nginx

- name: Check if certificate exists
  stat:
    path: /etc/letsencrypt/live/{{ ansible_fqdn }}/cert.pem
  register: cert

- name: Get current certificate info
  community.crypto.x509_certificate_info:
    path: /etc/letsencrypt/live/{{ ansible_fqdn }}/cert.pem
  register: certinfo

- name: Set fact to regenerate certificates if new domains are added
  set_fact:
    certbot_regenerate: yes
  when: item.name is defined and 'DNS:' + item.name not in certinfo.subject_alt_name
  loop: "{{ nginx_servers }}"

- name: Generate new certificate if one doesn't exist.
  command: certbot --nginx certonly --non-interactive --email {{ certbot_admin_email }} --agree-tos --expand --domains {{ ansible_fqdn }}{% for server in nginx_servers %}{% if server.name is defined %},{{ server.name }}{% endif %}{% endfor %}
  when: not cert.stat.exists or certbot_regenerate
  notify: reload nginx

- name: Configure certificate for nginx
  template:
    src: letsencrypt.conf
    dest: /etc/nginx/conf.d/letsencrypt.conf
  notify: reload nginx

