---

all:
  vars:
    ansible_user: '{{ lookup("env", "ANSIBLE_USERNAME") }}'
    ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'
  hosts:
    matrix.pikaviestin.fi:
    valvonta.pikaviestin.fi:
    tapahtumat.pikaviestin.fi:
    docker.pikaviestin.fi:

