---

all:
  vars:
    ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'
  hosts:
    matrix.pikaviestin.fi:
    valvonta.pikaviestin.fi:
    mastadon.pikaviestin.fi:
    docker.pikaviestin.fi:

