---

collections:
  - name: uumas.general
    version: '>=0.5.0'
  - name: uumas.docker
    version: '>=0.5.5'
  - name: pikaviestin.docker
    version: '>=0.0.1'
  - name: pikaviestin.matrix
    version: '>=0.0.8'
  - name: community.crypto

roles:
  - name: cloudalchemy.grafana
    version: '0.18.0'
