---

- hosts: matrix.pikaviestin.fi
  become: yes
  roles:
    - uumas.general.packages    # Installs useful packages
    - uumas.general.ssh         # Configures sshd
    - uumas.general.users       # Creates users
    - uumas.docker.docker       # Installs docker
    - nginx                     # Installs and configures nginx
    - matrix-synapse            # Installs and configures synapse
    - docker

