---

reverse_proxy_type: none

matrix_domain: pikaviestin.fi
matrix_server_domain: matrix.pikaviestin.fi
matrix_external_url: https://{{ matrix_server_domain }}

matrix_max_upload_size_mb: 200

matrix_media_repo_server: matrix-media.n.kapsi.fi

synapse_admin_contact: 'mailto:yllapito@pikaviestin.fi'
synapse_presence: yes
synapse_metrics: yes

synapse_psql_host: psql1.n.kapsi.fi
synapse_psql_user: matrix_ax

matrix_slidingsync_url: https://sliding-sync.matrix.pikaviestin.fi


matrix_auto_join_rooms:
  - '#aula:pikaviestin.fi'
  - '#matrix-suomi:kapsi.fi'

matrix_openidc_providers:
  - idp_id: authentik
    idp_name: Authentik
    discover: true
    issuer: "https://login.pikaviestin.fi/application/o/pikaviestin-matrix/"
    client_id: "52611cbe0a8e16c458026d4f7b3c966cd0acd549"
    client_secret: "{{ matrix_openidc_providers_authentik_client_secret }}"
    scopes:
      - "openid"
      - "profile"
    user_mapping_provider:
      config:
        localpart_template: "{{ '{{ user.preferred_username }}' }}"
        display_name_template: "{{ '{{ user.preferred_username }}' }}"

synapse_sso_client_whitelist:
  - https://chat.pikaviestin.fi/
  - https://cinny.pikaviestin.fi/

nginx_matrix_website_redirect: https://www.pikaviestin.fi

synapse_workers:
  generic_sync:
    - 8011
    - 8012
    - 8013
    - 8014
  generic_init_sync:
    - 8020
    - 8021
  generic_client:
    - 8022
  generic_pagination:
    - 8025
  generic_event_send:
    - 8026
  generic_login:
    - 8030
  generic_federation:
    - 8034
  generic_federation_send:
    - 8041
  event_persister:
    - 8046
  federation_sender:
    - 8056
  appservice:
    - 8066
  pusher:
    - 8071
  user_dir:
    - 8076
  frontend_proxy:
    - 8092

matrix_serve_wellknown_on_matrix_domain: true

nginx:
  http:
    server_tokens: 'off'
  ssl:
    ssl_protocols: 'TLSv1.2 TLSv1.3'
    ssl_prefer_server_ciphers: 'on'
