# {{ ansible_managed }}

[http.routers]
   [http.routers.mobilizon-rtr]
     entrypoints = "websecure"
     rule = "Host('jarkkaa.fi')"
     service = "mobilizon-svc"
     [http.routers.mobilizon-rtr.tls]
       certresolver = "le"

[http.services]
   [http.services.mobilizon-svc]
     [http.services.mobilizon-svc.loadBalancer]
       [[http.services.mobilizon-svc.loadBalancer.servers]]
         url = "http://91.232.156.56:4000"