---

nginx_confs: []

nginx_certbot: yes
certbot_regenerate: no

nginx_proxy_headers:
  X-Forwarded-For: '$remote_addr'
  X-Forwarded-Proto: '$scheme'
  Host: '$host'
  Upgrade: '$http_upgrade'
  Connection: '$connection_upgrade'

