ports:
  grafana_http: 3000
  prometheus_http: 9090

# Grafana related
grafana_use_provisioning: true
grafana_version: 8.3.3
grafana_url: https://{{ ansible_host }}/grafana/
grafana_server:
  serve_from_sub_path: true
grafana_auth:
  signout_redirect_url: https://login.pikaviestin.fi/application/o/grafana/end-session/
  disable_login_form: true
  oauth_auto_login: true
  generic_oauth:
    name: Authentik
    enabled: true
    client_id: 135e5017f52b164503357316c701cec702c100d4
    client_secret: "{{ SECRET_OAUTH_GRAFANA }}"
    scopes: openid email profile
    auth_url: https://login.pikaviestin.fi/application/o/authorize/
    token_url: https://login.pikaviestin.fi/application/o/token/
    api_url: https://login.pikaviestin.fi/application/o/userinfo/
    role_attribute_path: contains(groups[*] 'authentik Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor'

grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://127.0.0.1:9090/prom/'
    isDefault: true

# Needs to be figured out somehow, either via ForwardAuth from nginx or something else.
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/#oauth2
#prom_oauth2:
#  client_id: b78e0e229490b1b9b28a6c367a1771a9de1e0c58
#  client_secret: "{{ SECRET_OAUTH_PROM }}"
#  token_url: https://login.pikaviestin.fi/application/o/token/


# nginx
nginx:
  http:
    server_tokens: 'off'
  ssl:
    ssl_protocols: 'TLSv1.2 TLSv1.3'
    ssl_prefer_server_ciphers: 'on'

nginx_upstreams:
  grafana:
    location: "/grafana/"
    servers:
      - "{{ ports.grafana_http }}"
  prometheus:
    location: "/prom/"
    servers:
      - "{{ ports.prometheus_http }}"

nginx_servers:
  - name: "{{ ansible_host }}"
    reverse_proxy:
      - grafana
      - prometheus