---

- name: Set worker type
  set_fact:
    worker_type: "{{ item.key }}"

- name: Include default variables
  include_vars: defaults.yaml
- name: Include {{ worker_type }} variables
  include_vars: "{{ item }}"
  with_first_found:
    - files: 
        - "{{ worker_type }}.yaml"
      skip: yes

- name: Reset worker_ports
  set_fact:
    worker_ports: []
- name: Set worker_ports
  set_fact:
    worker_ports: "{{ item.value }}"
  when: item.value is iterable

- name: "Setup {{ worker_type }}(s) if they have listeners"
  include_tasks: worker_instance.yml
  loop: "{{ worker_ports }}"
  loop_control:
    loop_var: worker_port
    index_var: worker_index
  when: worker_ports|length != 0

- name: "Setup {{ worker_type }}(s) if they don't have listeners"
  include_tasks: worker_instance.yml
  when: worker_ports|length == 0

- name: Append synchrotron var
  set_fact:
    synapse_synchrotrons: "{{ synapse_synchrotrons + [ synchrotron_type ] }}"
  when: synchrotron_type is defined and synchrotron_type not in synapse_synchrotrons
