---

- name: Matrix Email Bridge Container
  docker_container:
   name: email_bridge
   image: ghcr.io/matrix-ax/matrix-emailbridge:latest
   pull: yes
   restart_policy: unless-stopped
   network_mode: host
   volumes:
    - /opt/docker/appdata/emailbrdige:/app/data
