---

- name: Create sliding sync container
  docker_container:
    name: sliding-sync
    image: ghcr.io/matrix-org/sliding-sync:latest@sha256:1789abdfa80c5486903aec0d0b9e9db1d3673cfdeb8f8d0cf02074534a2ef492
    pull: yes
    restart_policy: unless-stopped
    env:
      SYNCV3_SERVER: https://matrix.pikaviestin.fi
      SYNCV3_SECRET: "{{ sliding_sync_secret }}"
      SYNCV3_BINDADDR: :8008
      SYNCV3_DB: "user=matrix_ax_syncv3 password={{ sliding_sync_db_password }} dbname=matrix_ax_syncv3 sslmode=disable host=psql1.n.kapsi.fi"
    labels:
      traefik.enable: "true"
      traefik.http.routers.slidingsync-rtr.entrypoints: "websecure"
      traefik.http.routers.slidingsync-rtr.rule: Host("sliding-sync.matrix.pikaviestin.fi")
      traefik.http.routers.slidingsync-rtr.service: slidingsync-svc
      traefik.http.services.slidingsync-svc.loadbalancer.server.port: "8008"