---
- hosts: all
  roles:
    - uumas.general.packages    # Installs useful packages
    - uumas.general.ssh         # Configures sshd
    - uumas.general.users       # Creates users
    - node-exporter