---
- hosts: matrix.pikaviestin.fi
  roles:
    - nginx                     # Installs and configures nginx
    - matrix-synapse            # Installs and configures synapse
    - uumas.docker.docker       # Installs docker
    - docker                    # Installs Docker containers, currently Cinny, and Authentik