route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: matrix-default
receivers:
  - name: 'matrix-default'
    webhook_configs:
      - url: 'http://127.0.0.1:9088/alert'
